version: '2.1'
services:
  database:
    image: mysql
    ports:
      - '3306:3306'
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_PASSWORD=jan
      - MYSQL_USER=jan
      - MYSQL_DATABASE=jan
    healthcheck:
      test: ['CMD', 'bash', '-c', 'mysqladmin ping -h localhost && sleep 10']
      retries: 10
    container_name: database
  frontend:
    build: ./frontend
    ports:
      - '4200:4200'
    volumes:
      - ./frontend:/app
  authserver:
    build: ./authserver
    ports:
      - '3001:3001'
    depends_on:
      database:
        condition: service_healthy
  imageserver:
    build: ./imageserver
    ports:
      - '3201:80'
    depends_on:
      database:
        condition: service_healthy
  commentservice:
    build: ./comment
    ports:
      - '3202:80'
    depends_on:
      database:
        condition: service_healthy