version: '2.1'
services:
  database:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=jan
      - MYSQL_USER=jan
      - MYSQL_DATABASE=jan
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      retries: 10
    container_name: database
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  frontend:
    build: #./frontend
      # For build (with nginx)
      context: ./frontend
      dockerfile: Dockerfilebuild
    ports:
      # For build (with nginx)
      - '80:80'
      # - '4200:4200'
    volumes:
      - ./frontend:/app
      - /app/node_modules
  authserver:
    build: ./authserver
    restart: always
    ports:
      - '3001:3001'
    volumes:
      - ./authserver:/app
      - /app/node_modules
    depends_on:
      database:
        condition: service_healthy
  imageserver:
    build: ./imageserver
    # restart: always
    environment:
      - MYSQL_URI=mysql://jan:jan@database/jan
    volumes:
      - ./store-imageserver:/usr/src/app/storage:rw
    ports:
      - '3201:80'
    depends_on:
      database:
        condition: service_healthy
  commentservice:
    build: ./comment
    # restart: always
    environment:
      - MYSQL_URI=mysql://jan:jan@database/jan
    ports:
      - '3202:80'
    depends_on:
      database:
        condition: service_healthy
  shoppingservice:
    build: ./shoppingservice
    # restart: always
    environment:
      - MYSQL_URI=mysql://jan:jan@database/jan
    ports:
      - '3203:80'
      - '3204:8080'
    depends_on:
      database:
        condition: service_healthy
  coreservice:
    build: ./CoreService/CoreService
    ports:
      - '1337:80'
    depends_on:
      database:
        condition: service_healthy